/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testrunner1;

import org.tmatesoft.svn.core.SVNException;
import java.util.UUID;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *v
 * @author justin.mulcahy
 */
public class MainFrame extends javax.swing.JFrame  {
    
    
    public static String connectionURL = "jdbc:sqlserver://10.2.65.22:1433;databaseName=TestRunner;user=sa;password=Passw0rd";
    private int status;
    public static String uuid = UUID.randomUUID().toString();


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        PopulateDropdowns();
        PopulateSiteURL();
        PopulateClassName();
        PopulateClient();
        PopulateOPClassName();
        Language();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Browser = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StartTest = new javax.swing.JButton();
        TestClass = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TestMethod = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Account = new javax.swing.JTextField();
        SiteURL = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Language = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        ClientMachine = new javax.swing.JComboBox();
        Results = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        OPBrowser = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        OPSiteURL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        OPLanguage = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        OPTestClass = new javax.swing.JComboBox();
        OPTestMethod = new javax.swing.JComboBox();
        StartOnPemiseTest = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        OPClientMachine = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        NewCloud15 = new javax.swing.JButton();
        NewAcc15 = new javax.swing.JTextField();
        NewCloud14 = new javax.swing.JButton();
        NewAcc14 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        NewTestClass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        DeleteTest = new javax.swing.JButton();
        TESTADDDELETE = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Start72Suite = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Start73Suite = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        TestSuiteStarted = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Browser");

        Browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowserActionPerformed(evt);
            }
        });

        jLabel2.setText("Site URL");

        jLabel4.setText("Test Class");

        StartTest.setText("Start Test");
        StartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTestActionPerformed(evt);
            }
        });

        TestClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestClassActionPerformed(evt);
            }
        });

        jLabel6.setText("Test Method");

        TestMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blank" }));

        jLabel7.setText("Account");

        jLabel5.setText("Language");

        jLabel12.setText("Client Machine ");

        Results.setText("Results");
        Results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StartTest)
                        .addGap(18, 18, 18)
                        .addComponent(Results))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Browser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(TestMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(TestClass, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Browser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(SiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartTest)
                    .addComponent(Results))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cloud TestRunner", jPanel1);

        jLabel3.setText("Browser");

        OPBrowser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Firefox", "IE", "Chrome" }));

        jLabel8.setText("Site URL");

        OPSiteURL.setText("http://");
        OPSiteURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPSiteURLActionPerformed(evt);
            }
        });

        jLabel9.setText("Language");

        OPLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EN", "DE", "ES", "FR" }));

        jLabel10.setText("TestClass");

        jLabel11.setText("TestMethod");

        OPTestMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blank", "tests.Metadata.Metadata" }));

        StartOnPemiseTest.setText("Start Test");
        StartOnPemiseTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartOnPemiseTestActionPerformed(evt);
            }
        });

        jLabel21.setText("Client");

        OPClientMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPClientMachineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartOnPemiseTest)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OPTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OPLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(OPBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(OPSiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OPTestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OPClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(OPBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OPSiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(OPLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(OPTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(OPTestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(OPClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(StartOnPemiseTest)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("On-Premise TestRunner", jPanel2);

        NewCloud15.setText("Generate Cloud 2015R2 Account");
        NewCloud15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCloud15ActionPerformed(evt);
            }
        });

        NewAcc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAcc15ActionPerformed(evt);
            }
        });

        NewCloud14.setText("Generate Cloud 2014R2 Account");
        NewCloud14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCloud14ActionPerformed(evt);
            }
        });

        NewAcc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAcc14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NewCloud14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewCloud15, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewAcc15, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(NewAcc14))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCloud15)
                    .addComponent(NewAcc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewCloud14)
                    .addComponent(NewAcc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Cloud Account ", jPanel3);

        jLabel13.setText("Test ClassName: ");

        jButton2.setText("Add Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DeleteTest.setText("Delete Test");
        DeleteTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteTest))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(NewTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TESTADDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NewTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TESTADDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(DeleteTest))
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test Admin", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Security", jPanel5);

        jLabel14.setText("Start 7.2 Suite");

        Start72Suite.setText("Start");
        Start72Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start72SuiteActionPerformed(evt);
            }
        });

        jLabel15.setText("Start 7.3 Suite");

        Start73Suite.setText("Start");
        Start73Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start73SuiteActionPerformed(evt);
            }
        });

        jLabel16.setText("Start Q.A Staging Cloud Suite ");

        jButton5.setText("Start");

        jLabel17.setText("Start Pre Production Cloud Suite");

        jButton6.setText("Start");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("Start DevOne Cloud Suite ");

        jButton7.setText("Start");

        jLabel19.setText("Start DevFive Cloud Suite");

        jButton8.setText("Start");

        jLabel20.setText("Disable All Automated Runs");

        jButton10.setText("Disable");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Start73Suite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Start72Suite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                .addGap(57, 57, 57)
                .addComponent(TestSuiteStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(TestSuiteStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(Start72Suite))
                        .addGap(18, 18, 18)
                        .addComponent(Start73Suite))
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jButton5))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jButton8))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jenkins Suite Execution", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Test Suite Configuration", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TestClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestClassActionPerformed

    private void StartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestActionPerformed
        try {
            // TODO add your handling code here:
            String uuid = UUID.randomUUID().toString();
            String Browser1 = Browser.getSelectedItem().toString();
            String URL = SiteURL.getSelectedItem().toString();
            String Version = "Cloud(Professional)";
            String Logon = Account.getText();
            String ClassName = TestClass.getSelectedItem().toString();
            String Lang = Language.getSelectedItem().toString();
         
            //String MethodName = TestMethod.getSelectedItem().toString();
            String ProductVer = "7.2";
           
            if(Logon.equals("")){
           JOptionPane.showMessageDialog(null, "Account Logon cannot be blank... ");
            }
            else{

           
           
            //doInBackground();
            
             int n = JOptionPane.showConfirmDialog(null, "<html> Submit Test ?<br>Browser: "+Browser1+"<br>Version: "+Version+"<br>Logon: "+Logon+"<br>Test: "+ClassName+"<br>Language: "+Lang+"", uuid, JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.CANCEL_OPTION) {

            } else if (n == JOptionPane.OK_OPTION) {
                 Functions a=new Functions();
            a.CreateDirectories();
            a.checkoutCloud();
            a.CreateBatchFile();
            a.createTextXML(ClassName);
            
            a.createConfigCloud(Browser1,Version,URL,Logon,ProductVer,Lang);
            	RunTest t=new RunTest();

                t.displayGUI();
           
            a.reset();
            }
            } 
        } catch (SVNException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StartTestActionPerformed

    private void BrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrowserActionPerformed

    private void NewCloud15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCloud15ActionPerformed
         try {
            // TODO add your handling code here:
            Functions b=new Functions();
           String EMail = b.createCloudAccount();
           NewAcc15.setText(EMail);
           
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NewCloud15ActionPerformed

    private void NewAcc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAcc15ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_NewAcc15ActionPerformed

    private void OPSiteURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPSiteURLActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OPSiteURLActionPerformed

    private void StartOnPemiseTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartOnPemiseTestActionPerformed
        try {
            // TODO add your handling code here:
            
             String uuid = UUID.randomUUID().toString();
                String OPBrowser1 = OPBrowser.getSelectedItem().toString();
                String URL = OPSiteURL.getText();
                String Version = "On-Premise";
                String Logon = "admin";
                String ClassName = OPTestClass.getSelectedItem().toString();
                String Lang = OPLanguage.getSelectedItem().toString();
                //String MethodName = TestMethod.getSelectedItem().toString();
                String ProductVer = "7.3";
               if(URL.equals("")){
           JOptionPane.showMessageDialog(null, "Site URL Cannnot be Blank");
            }
            else{
                   
                    int n = JOptionPane.showConfirmDialog(null, "<html> Submit Test ?<br>Browser: "+OPBrowser1+"<br>Version: "+Version+"<br>Logon: "+Logon+"<br>Test: "+ClassName+"<br>Language: "+Lang+"", uuid, JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.CANCEL_OPTION) {

            } else if (n == JOptionPane.OK_OPTION) {
            	RunTest t=new RunTest();

                t.displayGUI();
                Functions a=new Functions();
                a.CreateDirectories();
                a.checkoutOnPrem();
                a.CreateBatchFile();
                a.createTextXML(ClassName);
                
                a.createConfigCloud(OPBrowser1,Version,URL,Logon,ProductVer,Lang);
                //doInBackground();
                RunTest test=new RunTest();
                test.displayGUI();
            }
               }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SVNException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_StartOnPemiseTestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String NewTest = NewTestClass.getText();
        AddTestClass(NewTest);
        TESTADDDELETE.setText("Test Added Successfully");
        PopulateDropdowns();
        NewTestClass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Start73SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start73SuiteActionPerformed
        // TODO add your handling code here:
         Functions a = new Functions();
        try {
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20Chrome%20Servers/build");
             a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20FF%20Servers/build");
              a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20IE%20Servers/build");
              TestSuiteStarted.setText("7.3 Suites Started Succesfully");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Start73SuiteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultsActionPerformed
        // TODO add your handling code here:
        
        PieChart.DispalyResults();
        
        
        
    }//GEN-LAST:event_ResultsActionPerformed

    private void DeleteTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTestActionPerformed
        // TODO add your handling code here:
        
        String NewTest = NewTestClass.getText();
        DeleteTestClass(NewTest);
        TESTADDDELETE.setText("Test Deleted Successfully");
    }//GEN-LAST:event_DeleteTestActionPerformed

    private void Start72SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start72SuiteActionPerformed
        // TODO add your handling code here:
        Functions a = new Functions();
        try {
            a.PostURL("http://192.168.118.159:8081/view/On-Premise%207.2%20Suites/job/Poll%20Build%20Folder%2072%20CRM%20Reboot%20VMs/build");
            TestSuiteStarted.setText("7.2 Suite Started Succesfully");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Start72SuiteActionPerformed

    private void OPClientMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPClientMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPClientMachineActionPerformed

    private void NewAcc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAcc14ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NewAcc14ActionPerformed

    private void NewCloud14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCloud14ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Functions b=new Functions();
           String Acc = b.createCloudAccount14();
           NewAcc14.setText(Acc);
           
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NewCloud14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Account;
    public javax.swing.JComboBox Browser;
    public javax.swing.JComboBox ClientMachine;
    private javax.swing.JButton DeleteTest;
    public javax.swing.JComboBox Language;
    private javax.swing.JTextField NewAcc14;
    public javax.swing.JTextField NewAcc15;
    private javax.swing.JButton NewCloud14;
    private javax.swing.JButton NewCloud15;
    public javax.swing.JTextField NewTestClass;
    public javax.swing.JComboBox OPBrowser;
    public javax.swing.JComboBox OPClientMachine;
    public javax.swing.JComboBox OPLanguage;
    public javax.swing.JTextField OPSiteURL;
    public javax.swing.JComboBox OPTestClass;
    public javax.swing.JComboBox OPTestMethod;
    private javax.swing.JButton Results;
    public javax.swing.JComboBox SiteURL;
    private javax.swing.JButton Start72Suite;
    private javax.swing.JButton Start73Suite;
    private javax.swing.JButton StartOnPemiseTest;
    public javax.swing.JButton StartTest;
    private javax.swing.JLabel TESTADDDELETE;
    public javax.swing.JComboBox TestClass;
    public javax.swing.JComboBox TestMethod;
    private javax.swing.JLabel TestSuiteStarted;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

   
    
    
       public JComboBox PopulateDropdowns() {
                 
             
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[BrowserType]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    Browser.addItem(rs.getString("Browser"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return Browser;
    }

       
       public JComboBox PopulateSiteURL() {
                 
                
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT URL,Environment FROM [TestRunner].[dbo].[SiteURL]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    SiteURL.addItem(rs.getString("URL"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return SiteURL;
    }
       
        public JComboBox PopulateClassName() {
                 
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[ClassName]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    TestClass.addItem(rs.getString("ClassName"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return TestClass;
    }
        
        public JComboBox PopulateOPClassName() {
                 
                
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[ClassName]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    OPTestClass.addItem(rs.getString("ClassName"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return OPTestClass;
    }
     
        
        
           public JComboBox PopulateClient() {
                 
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[Client]");

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    ClientMachine.addItem(rs.getString("Client"));
             
                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return ClientMachine;
    }
           
           
             public JComboBox Language() {
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[Language]");

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    Language.addItem(rs.getString("Language"));
             
                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                
                catch (SQLException e) {
                    e.printStackTrace();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
              
                        // Close Test connection
                   
                    
                    return Language;
    }
        
       
         private void AddTestClass(String NewTest) {
             
                // Change the connection string according to your db, ip, username and password
 
            try {
 
                            // Load the Driver class. 
                            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                            // If you are using any other database then load the right driver here.

                            //Create the connection using the static getConnection method
                            Connection con = DriverManager.getConnection (connectionURL);

                            //Create a Statement class to execute the SQL statement
                            java.sql.Statement stmt = con.createStatement();

                            //Execute the SQL statement and get the results in a Resultset
                           stmt.executeUpdate("INSERT INTO [TestRunner].[dbo].[ClassName]([ClassName])VALUES('"+NewTest+"')");

                            // Iterate through the ResultSet, displaying two values
                            // for each row using the getString method





                             // System.out.println("Name= " + rs.getString("ClassName"));
                        }
                        catch (SQLException e) {
                            e.printStackTrace();
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                        }
                        finally {
                            // Close Test connection
                            //con.close();
            }
    }
         
         private void DeleteTestClass(String NewTest) {
                // Change the connection string according to your db, ip, username and password
 
            try {
 
                            // Load the Driver class. 
                            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                            // If you are using any other database then load the right driver here.

                            //Create the connection using the static getConnection method
                            Connection con = DriverManager.getConnection (connectionURL);

                            //Create a Statement class to execute the SQL statement
                            java.sql.Statement stmt = con.createStatement();

                            //Execute the SQL statement and get the results in a Resultset
                           stmt.executeUpdate("DELETE FROM [TestRunner].[dbo].[ClassName] WHERE ClassName='"+NewTest+"'");

                            // Iterate through the ResultSet, displaying two values
                            // for each row using the getString method





                             // System.out.println("Name= " + rs.getString("ClassName"));
                        }
                        catch (SQLException e) {
                            e.printStackTrace();
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                        }
                        finally {
                            // Close Test connection
                            //con.close();
            }
    }
    
     
       
        
    } 
    

