/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testrunner1;

import org.tmatesoft.svn.core.SVNException;
import java.util.UUID;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *v
 * @author justin.mulcahy
 */
public class MainFrame extends javax.swing.JFrame  {
    
    
    public static String connectionURL = "jdbc:sqlserver://10.2.65.22:1433;databaseName=TestRunner;user=sa;password=Passw0rd";
    private int status;
    public static String uuid = UUID.randomUUID().toString();


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //PopulateDropdowns();
        PopulateSiteURL();
        PopulateClassName();
        PopulateClient();
        PopulateOPClassName();
        Language();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StartTest = new javax.swing.JButton();
        TestClass = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TestMethod = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Account = new javax.swing.JTextField();
        SiteURL = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Language = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        ClientMachine = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        OPBrowser = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        OPSiteURL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        OPLanguage = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        OPTestClass = new javax.swing.JComboBox();
        OPTestMethod = new javax.swing.JComboBox();
        StartOnPemiseTest = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        OPClientMachine = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        NewCloud15 = new javax.swing.JButton();
        NewAcc15 = new javax.swing.JTextField();
        NewCloud14 = new javax.swing.JButton();
        NewAcc14 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        NewTestClass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        DeleteTest = new javax.swing.JButton();
        TESTADDDELETE = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Start72Suite = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Start73Suite = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Disable = new javax.swing.JButton();
        TestSuiteStarted = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Enable = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultsTable = new javax.swing.JTable();
        CloudResults = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TotalTests = new javax.swing.JLabel();
        PassTests = new javax.swing.JLabel();
        FailTests = new javax.swing.JLabel();
        SkippedTests = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Site URL");

        jLabel4.setText("Test Class");

        StartTest.setText("Start Test");
        StartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTestActionPerformed(evt);
            }
        });

        TestClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestClassActionPerformed(evt);
            }
        });

        jLabel6.setText("Test Method");

        TestMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blank" }));

        jLabel7.setText("Account");

        jLabel5.setText("Language");

        jLabel12.setText("Client Machine ");

        jButton1.setText("Connect To VM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartTest)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(TestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TestClass, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(93, 93, 93)
                .addComponent(StartTest)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cloud TestRunner", jPanel1);

        jLabel3.setText("Browser");

        OPBrowser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Firefox", "IE", "Chrome" }));

        jLabel8.setText("Site URL");

        OPSiteURL.setText("http://");
        OPSiteURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPSiteURLActionPerformed(evt);
            }
        });

        jLabel9.setText("Language");

        OPLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EN", "DE", "ES", "FR" }));

        jLabel10.setText("TestClass");

        jLabel11.setText("TestMethod");

        OPTestMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blank", "tests.Metadata.Metadata" }));

        StartOnPemiseTest.setText("Start Test");
        StartOnPemiseTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartOnPemiseTestActionPerformed(evt);
            }
        });

        jLabel21.setText("Client");

        OPClientMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPClientMachineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartOnPemiseTest)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OPTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OPLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(OPBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(OPSiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OPTestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OPClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(OPBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OPSiteURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(OPLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(OPTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(OPTestMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(OPClientMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(StartOnPemiseTest)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("On-Premise TestRunner", jPanel2);

        NewCloud15.setText("Generate Cloud 2015R2 Account");
        NewCloud15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCloud15ActionPerformed(evt);
            }
        });

        NewAcc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAcc15ActionPerformed(evt);
            }
        });

        NewCloud14.setText("Generate Cloud 2014R2 Account");
        NewCloud14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCloud14ActionPerformed(evt);
            }
        });

        NewAcc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAcc14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NewCloud14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewCloud15, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewAcc15, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(NewAcc14))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCloud15)
                    .addComponent(NewAcc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewCloud14)
                    .addComponent(NewAcc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Cloud Account ", jPanel3);

        jLabel13.setText("Test ClassName: ");

        jButton2.setText("Add Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DeleteTest.setText("Delete Test");
        DeleteTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteTest))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(NewTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TESTADDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TESTADDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(NewTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(DeleteTest))
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test Admin", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Security", jPanel5);

        jLabel14.setText("Start 7.2 Suite");

        Start72Suite.setText("Start");
        Start72Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start72SuiteActionPerformed(evt);
            }
        });

        jLabel15.setText("Start 7.3 Suite");

        Start73Suite.setText("Start");
        Start73Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start73SuiteActionPerformed(evt);
            }
        });

        jLabel16.setText("Start Q.A Staging Cloud Suite ");

        jButton5.setText("Start");

        jLabel17.setText("Start Pre Production Cloud Suite");

        jButton6.setText("Start");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("Start DevOne Cloud Suite ");

        jButton7.setText("Start");

        jLabel19.setText("Start DevFive Cloud Suite");

        jButton8.setText("Start");

        jLabel20.setText("Disable All Automated Runs");

        Disable.setText("Disable");
        Disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableActionPerformed(evt);
            }
        });

        jLabel22.setText("Enable All Automated Runs");

        Enable.setText("Enable");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Start72Suite, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Start73Suite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Disable, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(Enable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(57, 57, 57)
                        .addComponent(TestSuiteStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Disable))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(Enable))
                        .addGap(7, 7, 7)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(TestSuiteStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Start72Suite))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Start73Suite))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jButton5))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jButton8))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jenkins Suite Execution", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Test Suite Configuration", jPanel7);

        ResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ResultsTable);

        CloudResults.setText("Cloud Professional");
        CloudResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloudResultsActionPerformed(evt);
            }
        });

        jButton3.setText("On-Premise 7.3");

        jButton4.setText("On-Premise 7.2");

        Label.setText("Total: ");

        jLabel1.setText("Pass:");

        jLabel23.setText("Fail:");

        jLabel24.setText("Skip:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalTests)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(CloudResults))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(PassTests)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FailTests)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(SkippedTests)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloudResults)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label)
                    .addComponent(jLabel1)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(TotalTests)
                    .addComponent(PassTests)
                    .addComponent(FailTests)
                    .addComponent(SkippedTests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nightly Results", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TestClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestClassActionPerformed

    private void StartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestActionPerformed
        try {
            // TODO add your handling code here:
            String uuid = UUID.randomUUID().toString();
            String Browser1 = ClientMachine.getSelectedItem().toString();
            String URL = SiteURL.getSelectedItem().toString();
            String Version = "Cloud(Professional)";
            String Logon = Account.getText();
            String ClassName = TestClass.getSelectedItem().toString();
            String Lang = Language.getSelectedItem().toString();
          
            //String MethodName = TestMethod.getSelectedItem().toString();
            String ProductVer = "7.2";
           
            if(Logon.equals("")){
           JOptionPane.showMessageDialog(null, "Account Logon cannot be blank... ");
            }
            else{

           
           
            //doInBackground();
            
             int n = JOptionPane.showConfirmDialog(null, "<html> Submit Test ?<br>Browser: "+Browser1+"<br>Version: "+Version+"<br>Logon: "+Logon+"<br>Test: "+ClassName+"<br>Language: "+Lang+"", uuid, JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.CANCEL_OPTION) {

            } else if (n == JOptionPane.OK_OPTION) {
                 Functions a=new Functions();
            a.CreateDirectories();
            a.checkoutCloud();
            a.CreateBatchFile();
            a.createTextXML(ClassName);
            
            a.createConfigCloud(Browser1,Version,URL,Logon,ProductVer,Lang);
            	RunTest t=new RunTest();

                t.displayGUI();
           
            a.reset();
            }
            } 
        } catch (SVNException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_StartTestActionPerformed

    private void NewCloud15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCloud15ActionPerformed
         try {
            // TODO add your handling code here:
            Functions b=new Functions();
           String EMail = b.createCloudAccount();
           NewAcc15.setText(EMail);
           
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_NewCloud15ActionPerformed

    private void NewAcc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAcc15ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_NewAcc15ActionPerformed

    private void OPSiteURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPSiteURLActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OPSiteURLActionPerformed

    private void StartOnPemiseTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartOnPemiseTestActionPerformed
        try {
            // TODO add your handling code here:
            
             String uuid = UUID.randomUUID().toString();
                String OPBrowser1 = OPBrowser.getSelectedItem().toString();
                String URL = OPSiteURL.getText();
                String Version = "On-Premise";
                String Logon = "admin";
                String ClassName = OPTestClass.getSelectedItem().toString();
                String Lang = OPLanguage.getSelectedItem().toString();
                //String MethodName = TestMethod.getSelectedItem().toString();
                String ProductVer = "7.3";
               if(URL.equals("")){
           JOptionPane.showMessageDialog(null, "Site URL Cannnot be Blank");
            }
            else{
                   
                    int n = JOptionPane.showConfirmDialog(null, "<html> Submit Test ?<br>Browser: "+OPBrowser1+"<br>Version: "+Version+"<br>Logon: "+Logon+"<br>Test: "+ClassName+"<br>Language: "+Lang+"", uuid, JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.CANCEL_OPTION) {

            } else if (n == JOptionPane.OK_OPTION) {
            	RunTest t=new RunTest();

                t.displayGUI();
                Functions a=new Functions();
                a.CreateDirectories();
                a.checkoutOnPrem();
                a.CreateBatchFile();
                a.createTextXML(ClassName);
                
                a.createConfigCloud(OPBrowser1,Version,URL,Logon,ProductVer,Lang);
                //doInBackground();
                RunTest test=new RunTest();
                test.displayGUI();
            }
               }
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        } catch (SVNException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_StartOnPemiseTestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String NewTest = NewTestClass.getText();
            if(NewTestClass.equals("")){
           JOptionPane.showMessageDialog(null, "Site URL Cannnot be Blank");
            
        AddTestClass(NewTest);
        TESTADDDELETE.setText("Test Added Successfully");
       //PopulateDropdowns();
        NewTestClass.setText("");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DeleteTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTestActionPerformed
        // TODO add your handling code here:
        if(NewTestClass.equals("")){
        String NewTest = NewTestClass.getText();
        DeleteTestClass(NewTest);
        TESTADDDELETE.setText("Test Deleted Successfully");
        }
    }//GEN-LAST:event_DeleteTestActionPerformed

    private void OPClientMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPClientMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPClientMachineActionPerformed

    private void NewAcc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAcc14ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NewAcc14ActionPerformed

    private void NewCloud14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCloud14ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Functions b=new Functions();
           String Acc = b.createCloudAccount14();
           NewAcc14.setText(Acc);
           
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_NewCloud14ActionPerformed

    private void CloudResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloudResultsActionPerformed
        // TODO add your handling code here:
try{                 
    
                    String date = new SimpleDateFormat("").format(new Date());
                   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection con = DriverManager.getConnection (connectionURL);
                    java.sql.Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT Max([Product]) as Product,[TestName],[MethodName],Max([Result])as Result,Max([Version])as Version,Max([Date]) as Date FROM [TestRunner].[dbo].[Results] where Date>'"+date+" 23:00:11.353' GROUP BY [TestName],[MethodName]ORDER BY [TestName]");

                    ResultSetMetaData md = rs.getMetaData();
                    int columnCount = md.getColumnCount();
                    Vector columns = new Vector(columnCount);

                  //store column names
                    for(int i=1; i<=columnCount; i++)
                      columns.add(md.getColumnName(i));

                  Vector data = new Vector();
                  Vector row;

                    while (rs.next()) {

                      row = new Vector(columnCount);
                         for(int i=1; i<=columnCount; i++)
                         {
                             row.add(rs.getString(i));
                         }
                         data.add(row);


                    }
         
                //Display in JTable
              DefaultTableModel tableModel = new DefaultTableModel(data, columns);   
              
                 ResultsTable.setModel(tableModel);
                rs.close();
   
    } catch (SQLException sqle) {
      JOptionPane.showMessageDialog(new JFrame(), sqle + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
 
        sqle.printStackTrace();
    } catch (ClassNotFoundException cnfe) {
        JOptionPane.showMessageDialog(new JFrame(), cnfe + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
         
        cnfe.printStackTrace();
    }
               
    
                   
    }//GEN-LAST:event_CloudResultsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ClientURL = ClientMachine.getSelectedItem().toString();
        try {
            URL W8FF = new URL("http://w8-1x64_en_ff1:3000/");
            URL W8CH = new URL("http://w8-1x64_en_ch_1:3000/");
            /*URL W8IE = new URL("");
            URL W8FR = new URL("");
            URL W8DE = new URL("");
            URL W8ES = new URL("");*/
            
            if(ClientURL.equalsIgnoreCase("Win8.1x64 Firefox EN")){
                Functions c = new Functions();
            c.openWebpage(W8FF);
            }
            
            if(ClientURL.equalsIgnoreCase("Win8.1x64 Chrome EN")){
                Functions c = new Functions();
            c.openWebpage(W8CH);
            }
            /*if(ClientURL.equalsIgnoreCase("Win8.1x64 IE EN")){
                Functions c = new Functions();
            c.openWebpage(W8IE);
            }
            if(ClientURL.equalsIgnoreCase("Win8.1x64 Firefox DE")){
                Functions c = new Functions();
            c.openWebpage(W8DE);
            }
             if(ClientURL.equalsIgnoreCase("Win8.1x64 Firefox FR")){
                Functions c = new Functions();
            c.openWebpage(W8FR);
            }
             if(ClientURL.equalsIgnoreCase("Win8.1x64 Firefox ES")){
                Functions c = new Functions();
            c.openWebpage(W8ES);
            }*/
            
            
        } catch (MalformedURLException ex) {
           JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
      
            
            
            
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisableActionPerformed
        // TODO add your handling code here:
        Functions a = new Functions();
        try {
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20FF%20Servers/disable");
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20IE%20Servers/disable");
            a.PostURL("http://192.168.118.159:8081/job/7.3%20Chrome%20Servers/disable");
            a.PostURL("http://192.168.118.159:8081/view/On-Premise%207.2%20Suites/job/Poll%20Build%20Folder%2072%20CRM%20Reboot%20VMs/disable");

            TestSuiteStarted.setText("All Suites Disabled");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_DisableActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Start73SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start73SuiteActionPerformed
        // TODO add your handling code here:
        Functions a = new Functions();
        try {
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20Chrome%20Servers/build");
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20FF%20Servers/build");
            a.PostURL("http://192.168.118.159:8081/job/Revert%207.3%20IE%20Servers/build");
            TestSuiteStarted.setText("7.3 Suites Started Succesfully");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Start73SuiteActionPerformed

    private void Start72SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start72SuiteActionPerformed
        // TODO add your handling code here:
        Functions a = new Functions();
        try {
            a.PostURL("http://192.168.118.159:8081/view/On-Premise%207.2%20Suites/job/Poll%20Build%20Folder%2072%20CRM%20Reboot%20VMs/build");
            TestSuiteStarted.setText("7.2 Suite Started Succesfully");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Start72SuiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Account;
    public javax.swing.JComboBox ClientMachine;
    private javax.swing.JButton CloudResults;
    private javax.swing.JButton DeleteTest;
    private javax.swing.JButton Disable;
    private javax.swing.JButton Enable;
    private javax.swing.JLabel FailTests;
    public javax.swing.JLabel Label;
    public javax.swing.JComboBox Language;
    private javax.swing.JTextField NewAcc14;
    public javax.swing.JTextField NewAcc15;
    private javax.swing.JButton NewCloud14;
    private javax.swing.JButton NewCloud15;
    public javax.swing.JTextField NewTestClass;
    public javax.swing.JComboBox OPBrowser;
    public javax.swing.JComboBox OPClientMachine;
    public javax.swing.JComboBox OPLanguage;
    public javax.swing.JTextField OPSiteURL;
    public javax.swing.JComboBox OPTestClass;
    public javax.swing.JComboBox OPTestMethod;
    public javax.swing.JLabel PassTests;
    public javax.swing.JTable ResultsTable;
    public javax.swing.JComboBox SiteURL;
    private javax.swing.JLabel SkippedTests;
    private javax.swing.JButton Start72Suite;
    private javax.swing.JButton Start73Suite;
    private javax.swing.JButton StartOnPemiseTest;
    public javax.swing.JButton StartTest;
    private javax.swing.JLabel TESTADDDELETE;
    public javax.swing.JComboBox TestClass;
    public javax.swing.JComboBox TestMethod;
    private javax.swing.JLabel TestSuiteStarted;
    public javax.swing.JLabel TotalTests;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

   
    
    
  /*     public JComboBox PopulateDropdowns() {
                 
             
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[BrowserType]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    Browser.addItem(rs.getString("Browser"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                   JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return Browser;
    }
*/
       
       public JComboBox PopulateSiteURL() {
                 
                
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT URL,Environment FROM [TestRunner].[dbo].[SiteURL]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    SiteURL.addItem(rs.getString("URL"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return SiteURL;
    }
       
        public JComboBox PopulateClassName() {
                 
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[ClassName]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    TestClass.addItem(rs.getString("ClassName"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return TestClass;
    }
        
        public JComboBox PopulateOPClassName() {
                 
                
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[ClassName]");
                    

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    OPTestClass.addItem(rs.getString("ClassName"));

                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return OPTestClass;
    }
     
        
        
           public JComboBox PopulateClient() {
                 
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[Client]");

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    ClientMachine.addItem(rs.getString("Client"));
             
                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                
                catch (SQLException e) {
                   JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return ClientMachine;
    }
           
           
             public JComboBox Language() {
                 
                // Change the connection string according to your db, ip, username and password

                try {

                    // Load the Driver class. 
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    // If you are using any other database then load the right driver here.

                    //Create the connection using the static getConnection method
                    Connection con = DriverManager.getConnection (connectionURL);

                    //Create a Statement class to execute the SQL statement
                    java.sql.Statement stmt = con.createStatement();

                    //Execute the SQL statement and get the results in a Resultset
                    ResultSet rs = stmt.executeQuery("SELECT  *FROM [TestRunner].[dbo].[Language]");

                    // Iterate through the ResultSet, displaying two values
                    // for each row using the getString method

                    while (rs.next())
                    Language.addItem(rs.getString("Language"));
             
                     con.close();

                     // System.out.println("Name= " + rs.getString("ClassName"));
                }
                
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                }
              
                        // Close Test connection
                   
                    
                    return Language;
    }
        
       
         private void AddTestClass(String NewTest) {
             
                // Change the connection string according to your db, ip, username and password
 
            try {
 
                            // Load the Driver class. 
                            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                            // If you are using any other database then load the right driver here.

                            //Create the connection using the static getConnection method
                            Connection con = DriverManager.getConnection (connectionURL);

                            //Create a Statement class to execute the SQL statement
                            java.sql.Statement stmt = con.createStatement();

                            //Execute the SQL statement and get the results in a Resultset
                           stmt.executeUpdate("INSERT INTO [TestRunner].[dbo].[ClassName]([ClassName])VALUES('"+NewTest+"')");

                            // Iterate through the ResultSet, displaying two values
                            // for each row using the getString method





                             // System.out.println("Name= " + rs.getString("ClassName"));
                        }
                        catch (SQLException e) {
                            JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        finally {
                            // Close Test connection
                            //con.close();
            }
    }
         
         private void DeleteTestClass(String NewTest) {
                // Change the connection string according to your db, ip, username and password
 
            try {
 
                            // Load the Driver class. 
                            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                            // If you are using any other database then load the right driver here.

                            //Create the connection using the static getConnection method
                            Connection con = DriverManager.getConnection (connectionURL);

                            //Create a Statement class to execute the SQL statement
                            java.sql.Statement stmt = con.createStatement();

                            //Execute the SQL statement and get the results in a Resultset
                           stmt.executeUpdate("DELETE FROM [TestRunner].[dbo].[ClassName] WHERE ClassName='"+NewTest+"'");

                            // Iterate through the ResultSet, displaying two values
                            // for each row using the getString method





                             // System.out.println("Name= " + rs.getString("ClassName"));
                        }
                        catch (SQLException e) {
                           JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(new JFrame(), e + "\n"+"Please contact your system administrator.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        finally {
                            // Close Test connection
                            //con.close();
            }
    }
         
          private DefaultTableModel BuildResultsTable(ResultSet rs) throws SQLException {
                // Change the connection string according to your db, ip, username and password
 
               ResultSetMetaData metaData = rs.getMetaData();

                // names of columns
                Vector<String> columnNames = new Vector<String>();
                int columnCount = metaData.getColumnCount();
                for (int column = 1; column <= columnCount; column++) {
                    columnNames.add(metaData.getColumnName(column));
                }

                // data of the table
                Vector<Vector<Object>> data = new Vector<Vector<Object>>();
                while (rs.next()) {
                    Vector<Object> vector = new Vector<Object>();
                    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                        vector.add(rs.getObject(columnIndex));
                    }
                    data.add(vector);
                }

                return new DefaultTableModel(data, columnNames);
                }

     
       
        
    } 
    

